### ISSUE TITLE
32 bit or 64 bit Emulator

### ISSUE THREAD

**Issue by akarsh** [jangrewe/gitlab-ci-android#16]
Hi @jangrewe ,

I used the docker image for testing the gitlab-ci.
Have you tried functional tests in gitlab-ci for any android project ?

I tried to use `android-sdk-linux/tools/emulator -avd test -no-window -no-audio`
I ended up with errors of 32 bit.
If you have tried emulator 64 bit `emulator64-x86` ?

**Comment by jangrewe** [comment]
Hi @akarsh, i haven't used the emulator in this image at all, but please give some feedback if you figure it out!

**Comment by sczerwinski** [comment]
Hi @jangrewe and @akarsh,

I got to the point, where I'm installing required packages and starting the emulator:
```yml
androidTests:
  stage: test
  script:
    - apt-get -qq update && apt-get install -qqy --no-install-recommends qemu-kvm && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    - /sdk/tools/bin/sdkmanager --verbose 'system-images;android-25;google_apis;x86_64'
    - echo "no" | /sdk/tools/bin/avdmanager create avd -f -n api25 -k 'system-images;android-25;google_apis;x86_64' -d "pixel" -c 128M
    - echo "no" | /sdk/tools/emulator -avd api25 -wipe-data -noaudio -no-window -gpu off -verbose -qemu -vnc :2 &
    - timeout 180 /sdk/platform-tools/adb wait-for-device
    - ./gradlew cAT --stacktrace
```

Unfortunately, shared runners on gitlab.com seem to have KVM disabled in BIOS, so I end up with the following error:
```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
```
