### ISSUE TITLE
Allow override of SDK version

### ISSUE THREAD

**Issue by gsantner** [jangrewe/gitlab-ci-android#3]
Please allow override of SDK / Build Tools version.

I tried to override variables with this .gitlab-ci.yml file:

```
image: jangrewe/gitlab-ci-android

variables:
  VERSION_BUILD_TOOLS: "24.0.0"
  VERSION_TARGET_SDK: "24"
  VERSION_SDK_TOOLS: "25.1.7"

stages:
  - build
...
...
```

...but appareantly it didn't work.

Does sombody have an suggestion how to resolve this?
If the issue can be resolved, some kind of documentation should be there.

Here is for example a travis CI build file (as a reference):

```
language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools     # see https://github.com/travis-ci/travis-ci/issues/5036
    - android-23
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build check --stacktrace
```

Thanks for any suggestion :)
