### ISSUE TITLE
Could not find ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by javaherisaber** [jangrewe/gitlab-ci-android#67]
There is an error in runner console:
```
SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file
```

I tried to download command line tool and set sdk path manually
but it didn't work also

**Comment by jangrewe** [comment]
I'm not sure what you're doing to get this error message, but if used properly it definitely works as expected.

Just to confirm that `ANDROID_SDK_ROOT` is indeed defined by default:
```
$ docker run --rm jangrewe/gitlab-ci-android:30 env | grep ANDROID_SDK_ROOT
ANDROID_SDK_ROOT=/sdk
```

Maybe share your script so i can have a look what's wrong there?

**Comment by javaherisaber** [comment]
Here is the script:
```yml
image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  tags: [master]
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  interruptible: true
  stage: test
  tags: [master]
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

```
